### ISSUE TITLE
Expression data not available

### ISSUE THREAD

**Issue by sktowusuansah** [AmichayAfriat/SpatioTemporal_malaria_liver_stage_atlas#2]
Hello, is the expression data publicly accessible? I would like to explore the dataset either raw or processed.

**Comment by AmichayAfriat** [comment]
It is!
Data generated in this study have been deposited in the Gene Expression Omnibus with the accession code [GSE181725](http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE181725). Source data for Figs. [2a–c](https://www.nature.com/articles/s41586-022-05406-5#Fig2), [3b,d,f,h](https://www.nature.com/articles/s41586-022-05406-5#Fig3) and [4d,j](https://www.nature.com/articles/s41586-022-05406-5#Fig4) and Extended Data Figs. [2e–g](https://www.nature.com/articles/s41586-022-05406-5#Fig6), [3a,c,g,h](https://www.nature.com/articles/s41586-022-05406-5#Fig7), [4a,b](https://www.nature.com/articles/s41586-022-05406-5#Fig8), [5d,e](https://www.nature.com/articles/s41586-022-05406-5#Fig9), [7a–d](https://www.nature.com/articles/s41586-022-05406-5#Fig11), [8e,f](https://www.nature.com/articles/s41586-022-05406-5#Fig12), [9g–i](https://www.nature.com/articles/s41586-022-05406-5#Fig13) and [10a–m](https://www.nature.com/articles/s41586-022-05406-5#Fig14) are available at https://doi.org/10.5281/zenodo.7081863.

You can also explore the data using cellxgene at:
https://plasmodb.org/cellxgene/view/pberANKA_afriat_combined_cellxgene_RSRC.h5ad/

**Comment by sktowusuansah** [comment]
Thank you. Very much appreciated.

Best regards.
